[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.31.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["homebrew", "shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Homebrew tap to publish formulas to
tap = "rgodha24/homebrew-tap"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "./publish-crates"]
# Run 'dist plan' on pull requests
pr-run-mode = "plan"
