[package]
name = "ghfs"
version = "0.1.0"
edition = "2024"

[dependencies]
ghfs-fs = { path = "../ghfs-fs" }
ghfs-cache = { path = "../ghfs-cache" }
ghfs-types = { path = "../ghfs-types" }
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
