[package]
name = "ghfs-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
ghfs-types = { path = "../ghfs-types" }
ghfs-cache = { path = "../ghfs-cache" }
dashmap = "6"
fuser = "0.15"
libc = "0.2"
log = "0.4"
